theme_name = "config"
base1 = "#09090b"
base2 = "#18181b"
primary = "#00a6f4"
accent = "#615fff"
success = "#00bc7d"
warning = "#efb100"
danger = "#fb2c36"
text = "#d4d4d4"
text_muted = "#737373"
text_bright = "#f5f5f5"
selected = "#fd9a00"
