theme_name = "config"
base1 = "oklch(14.1% 0.005 285.823)"
base2 = "oklch(21% 0.006 285.885)"
primary = "oklch(68.5% 0.169 237.323)"
accent = "oklch(58.5% 0.233 277.117)"
success = "oklch(69.6% 0.17 162.48)"
warning = "oklch(79.5% 0.184 86.047)"
danger = "oklch(63.7% 0.237 25.331)"
text = "oklch(87% 0 0)"
text_muted = "oklch(55.6% 0 0)"
text_bright = "oklch(97% 0.001 106.424)"
selected = "oklch(76.9% 0.188 70.08)"
